(* https://www.w3.org/TR/xml/#sec-notation *)

Entry = (ImportDecl | IngressDecl | RuleDecl)*

InputDecl = "input", #x20, identifier, #x20, "{", S*, dataList, S*, "}";
ActionDecl = "action" #x20 identifier #x20 "{" S* actionSection S* "}";
actionSection = "target", ":", dataList;

dataList = data 
         | data #xA dataList;
data = identifier, (";" | "{", S*, variableList, S*, "}");

RuleDecl = "rule", #x20, identifier, "(", identifier+, ")", #x20 , "{", ruleSection, "}";
ruleSection = "strings", ":", (#xA, pattern)+
            | "match", ":", (#xA condition)+;
pattern = patternName, #x20, "=", #x20, patternExpr;
patternExpr = stringExpr, #x20, identifier* 
               | "{", (#x20* hexExpr)+, #x20*, "}"; 
hexExpr = ([0-9a-fA-F][0-9a-fA-F]) 
        | "??";
condition = "!"?, patternName, (#x20, ("&" | "|"), #x20, "!"?, string)*
          | "any" 
          | "all"
          | "none";
patternName = "$", identifier; 

variableList = variable | variable #xA variableList;
variable = identifier, #x20, "=", #x20, variableExpr;
variableExpr = string 
             | integer 
             | double
             | boolean
             | identifier;
integer = [0-9]+;
double = [0-9]+, ".", [0-9]+;
string = #x22, Char+, #x22;
boolean = "true" | "false";
identifier = [a-zA-Z_]+, [0-9]*;
S = (#x20 | #x9 | #xA)+; 
(* any Unicode character, excluding the surrogate blocks, FFFE, and FFFF. *)
Char = #x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF];



(* Example
-
import "myprovider.py" as p
import "myaction.py" as a

ingress data : p.es {
    input:
        $index = "mydata"
        $username = env.something
        $password = env.password
        $range = "30 seconds"
}

rule OutsideWorkHours {     
    match:
        $data.username AS $name
        unixtime($data.timestamp).hour AS $hour

    condition:
        $hour > 17 AND $hour < 9 AND $name
    
    target:
        a.notifyAdmin("[OusideWorkHours] "+ $name)
}

rule BruteForce {
    match:
        $data.username AS $name
        unixtime($data.timestamp) OVER 1h AS $found

    condition:
        #found > 30 AND $name
    
    target:
        a.notifyAdmin("[Bruteforce] "+ $name + " " + #found)
}

*)
